services:
  fuseki:
    image: stain/jena-fuseki
    container_name: wfh-fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - jena-data:/fuseki
      - ./fuseki-config.ttl:/fuseki/config.ttl
      - ./fuseki-vocabulary.ttl:/fuseki/vocabulary.ttl
      #- ../workflow-output/output/workflowhub-graph.ttl:/fuseki/data.ttl
    networks:
      - wfh
    healthcheck:
      test: >
        curl --silent --fail --user admin:admin http://localhost:3030/$/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      
  trifid:
    image: ghcr.io/zazuko/trifid
    container_name: wfh-trifid
    environment:
      - DATASET_BASE_URL=
      - SPARQL_ENDPOINT_URL=http://wfh-fuseki:3030/wfh/query
      - SPARQL_USER=admin
      - SPARQL_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - fuseki
    networks:
      - wfh

  # blueprint-configurator:
  #   build:
  #     context: blueprint-ui-config-initializer
  #     dockerfile_inline: |
  #       FROM node:24
  #       WORKDIR configurator
  #       COPY . .
  #       RUN npm ci
  #       ENTRYPOINT ./run.sh
  #   container_name: wfh-blueprint-config
  #   environment:
  #     - SPARQL_ENDPOINT=http://wfh-fuseki:3030/wfh/query
  #     - SPARQL_USER=admin
  #     - SPARQL_PASS=admin
  #   volumes:
  #     - jena-data:/config/
  #   depends_on:
  #     fuseki:
  #       condition: service_healthy
  #   networks:
  #     - wfh
      
  blueprint:
    image: ghcr.io/zazuko/blueprint
    container_name: wfh-blueprint
    environment:
      # Set up for local dev / demo but can be adapted by using an externally
      # resolvable URL e.g. ENDPOINT_URL=https://trifid.oliver-woolland-rse.uk/query
      - ENDPOINT_URL=http://localhost:8080/query
      - SPARQL_CONSOLE_URL=http://localhost:8080/sparql#query
      - GRAPH_EXPLORER_URL=http://localhost:8080/graph-explorer/?resource
      - FULL_TEXT_SEARCH_DIALECT=fuseki
    ports:
      - "4200:80"
    depends_on:
      - trifid
      #- blueprint-configurator
    networks:
      - wfh

volumes:
  jena-data:
    name: jena-data

networks:
  wfh:
    name: wfh
