name: Build and publish knowledge graph

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t knowledgegraph .

      - name: Run container to generate TTL
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/workflow-output:/app/workflow-output \
            knowledgegraph \
            --config max-workflow-id=10 \
            --config output-graph="workflowhub-graph.ttl" \
            --config output-dir=output

      - name: debug file location
        run: |
          tree ${{ github.workspace }}

      - name: Upload TTL artifact
        uses: actions/upload-artifact@v4
        with:
          name: "workflowhub-graph.ttl"
          path: ${{ github.workspace }}/workflow-output/output/workflowhub-graph.ttl
